"""update code execution model

Revision ID: 0c0c8e66ac42
Revises: 3cc225519028
Create Date: 2024-05-24 19:23:27.172294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0c8e66ac42'
down_revision = '3cc225519028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_code_executions')
    with op.batch_alter_table('code_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), nullable=False, server_default='python'))
        batch_op.add_column(sa.Column('timer', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_code',
               existing_type=sa.TEXT(),
               nullable=False)

    # Update server_default to None after setting the column values
    with op.batch_alter_table('code_executions', schema=None) as batch_op:
        batch_op.alter_column('language', server_default=None)
        batch_op.alter_column('timer', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_executions', schema=None) as batch_op:
        batch_op.alter_column('user_code',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('language')
        batch_op.drop_column('timer')

    op.create_table('_alembic_tmp_code_executions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('user_code', sa.TEXT(), nullable=False),
    sa.Column('code_output', sa.TEXT(), nullable=True),
    sa.Column('language', sa.VARCHAR(), nullable=False),
    sa.Column('timer', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
