"""update code execution model with a relationship

Revision ID: 34815ab5fc3a
Revises: 0c0c8e66ac42
Create Date: 2024-05-24 19:40:44.650963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34815ab5fc3a'
down_revision = '0c0c8e66ac42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_executions', schema=None) as batch_op:
        batch_op.drop_column('timer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timer', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
