"""create tables code_execution

Revision ID: 54cc5ece397b
Revises: df8d173ae230
Create Date: 2024-05-25 20:06:24.383951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54cc5ece397b'
down_revision = 'df8d173ae230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_code', sa.Text(), nullable=False),
    sa.Column('code_output', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('timer', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_executions')
    # ### end Alembic commands ###
