"""update assessment_score  model by deleting assessment  relationship

Revision ID: c4fa3db828ae
Revises: 34815ab5fc3a
Create Date: 2024-05-24 21:36:04.629608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fa3db828ae'
down_revision = '34815ab5fc3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_scores', schema=None) as batch_op:
        # Drop the column 'assessment_id'
        batch_op.drop_column('assessment_id')

    with op.batch_alter_table('code_executions', schema=None) as batch_op:
        # Add a new column 'timer' with type DateTime and nullable=True
        batch_op.add_column(sa.Column('timer', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_executions', schema=None) as batch_op:
        # Drop the column 'timer'
        batch_op.drop_column('timer')

    with op.batch_alter_table('assessment_scores', schema=None) as batch_op:
        # Add the column 'assessment_id' with type INTEGER and nullable=False
        batch_op.add_column(sa.Column('assessment_id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
