"""add test table and association table with code challenges table

Revision ID: e8442fe2ae2d
Revises: fddc4897d8d7
Create Date: 2024-05-22 10:32:54.500218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8442fe2ae2d'
down_revision = 'fddc4897d8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_code_challenge_association',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('code_challenge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['code_challenge_id'], ['code_challenges.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('test_id', 'code_challenge_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_code_challenge_association')
    op.drop_table('tests')
    # ### end Alembic commands ###
