"""Change timer column data type to Integer

Revision ID: e90094d0be92
Revises: 0681462c6d3e
Create Date: 2024-05-26 14:45:09.018771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90094d0be92'
down_revision = '0681462c6d3e'
branch_labels = None
depends_on = None


def upgrade():
    # Change the data type of the timer column to integer
    with op.batch_alter_table('code_executions', schema=None) as batch_op:
        batch_op.alter_column('timer',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True,
               using='timer::INTEGER')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_executions', schema=None) as batch_op:
        batch_op.alter_column('timer',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
